# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ceppelli.github.io
author: by me
#email: luca@ceppelli.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: "@"
copyright: "Copyright Â© Luca Ceppelli 2019"
#google_analytics: UA-91228915-1
show_downloads: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ceppelli.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lucaceppelli
github_username:  ceppelli
linkedin_username:  lucaceppelli
linkedin_username_id:  luca-ceppelli-66b6794

# Build settings         minima jekyll-swiss jekyll-theme-cayman jekyll-theme-slate
markdown: kramdown
theme: minima
# highlighter: rouge


# permalink: /:categories/:year/:month/:day/:title.html
# permalink: /:year/:month/:day/:title.html
# permalink: /:month-:day-:year/:title.html

#permalink:  /posts/:year:month:day-:title.html
permalink:  /posts/:title/

permalink:  /notes/:title/


collections:
  notes:
    output: true
    permalink:  /notes/:title/

# github-pages plugins
# Default
# - jekyll-coffeescript
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-paginate
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings
# Optional
# - jekyll-feed
# - jekyll-redirect-from
# - jekyll-seo-tag  # https://github.com/jekyll/jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-avatar
# - jemoji
# - jekyll-mentions
# - jekyll-include-cache

plugins:
  - jekyll-redirect-from
  - jekyll-avatar
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-scalafiddle
  # - jekyll-seo-tag  # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.loc
  - skills-app
  - skills-app-old

